#if 0
#elif defined(__arm64__) && __arm64__
// Generated by Apple Swift version 5.9 (swiftlang-5.9.0.128.108 clang-1500.0.40.1)
#ifndef BRAINTREEPAYPALNATIVECHECKOUT_SWIFT_H
#define BRAINTREEPAYPALNATIVECHECKOUT_SWIFT_H
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wgcc-compat"

#if !defined(__has_include)
# define __has_include(x) 0
#endif
#if !defined(__has_attribute)
# define __has_attribute(x) 0
#endif
#if !defined(__has_feature)
# define __has_feature(x) 0
#endif
#if !defined(__has_warning)
# define __has_warning(x) 0
#endif

#if __has_include(<swift/objc-prologue.h>)
# include <swift/objc-prologue.h>
#endif

#pragma clang diagnostic ignored "-Wauto-import"
#if defined(__OBJC__)
#include <Foundation/Foundation.h>
#endif
#if defined(__cplusplus)
#include <cstdint>
#include <cstddef>
#include <cstdbool>
#include <cstring>
#include <stdlib.h>
#include <new>
#include <type_traits>
#else
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>
#include <string.h>
#endif
#if defined(__cplusplus)
#if defined(__arm64e__) && __has_include(<ptrauth.h>)
# include <ptrauth.h>
#else
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wreserved-macro-identifier"
# ifndef __ptrauth_swift_value_witness_function_pointer
#  define __ptrauth_swift_value_witness_function_pointer(x)
# endif
# ifndef __ptrauth_swift_class_method_pointer
#  define __ptrauth_swift_class_method_pointer(x)
# endif
#pragma clang diagnostic pop
#endif
#endif

#if !defined(SWIFT_TYPEDEFS)
# define SWIFT_TYPEDEFS 1
# if __has_include(<uchar.h>)
#  include <uchar.h>
# elif !defined(__cplusplus)
typedef uint_least16_t char16_t;
typedef uint_least32_t char32_t;
# endif
typedef float swift_float2  __attribute__((__ext_vector_type__(2)));
typedef float swift_float3  __attribute__((__ext_vector_type__(3)));
typedef float swift_float4  __attribute__((__ext_vector_type__(4)));
typedef double swift_double2  __attribute__((__ext_vector_type__(2)));
typedef double swift_double3  __attribute__((__ext_vector_type__(3)));
typedef double swift_double4  __attribute__((__ext_vector_type__(4)));
typedef int swift_int2  __attribute__((__ext_vector_type__(2)));
typedef int swift_int3  __attribute__((__ext_vector_type__(3)));
typedef int swift_int4  __attribute__((__ext_vector_type__(4)));
typedef unsigned int swift_uint2  __attribute__((__ext_vector_type__(2)));
typedef unsigned int swift_uint3  __attribute__((__ext_vector_type__(3)));
typedef unsigned int swift_uint4  __attribute__((__ext_vector_type__(4)));
#endif

#if !defined(SWIFT_PASTE)
# define SWIFT_PASTE_HELPER(x, y) x##y
# define SWIFT_PASTE(x, y) SWIFT_PASTE_HELPER(x, y)
#endif
#if !defined(SWIFT_METATYPE)
# define SWIFT_METATYPE(X) Class
#endif
#if !defined(SWIFT_CLASS_PROPERTY)
# if __has_feature(objc_class_property)
#  define SWIFT_CLASS_PROPERTY(...) __VA_ARGS__
# else
#  define SWIFT_CLASS_PROPERTY(...) 
# endif
#endif
#if !defined(SWIFT_RUNTIME_NAME)
# if __has_attribute(objc_runtime_name)
#  define SWIFT_RUNTIME_NAME(X) __attribute__((objc_runtime_name(X)))
# else
#  define SWIFT_RUNTIME_NAME(X) 
# endif
#endif
#if !defined(SWIFT_COMPILE_NAME)
# if __has_attribute(swift_name)
#  define SWIFT_COMPILE_NAME(X) __attribute__((swift_name(X)))
# else
#  define SWIFT_COMPILE_NAME(X) 
# endif
#endif
#if !defined(SWIFT_METHOD_FAMILY)
# if __has_attribute(objc_method_family)
#  define SWIFT_METHOD_FAMILY(X) __attribute__((objc_method_family(X)))
# else
#  define SWIFT_METHOD_FAMILY(X) 
# endif
#endif
#if !defined(SWIFT_NOESCAPE)
# if __has_attribute(noescape)
#  define SWIFT_NOESCAPE __attribute__((noescape))
# else
#  define SWIFT_NOESCAPE 
# endif
#endif
#if !defined(SWIFT_RELEASES_ARGUMENT)
# if __has_attribute(ns_consumed)
#  define SWIFT_RELEASES_ARGUMENT __attribute__((ns_consumed))
# else
#  define SWIFT_RELEASES_ARGUMENT 
# endif
#endif
#if !defined(SWIFT_WARN_UNUSED_RESULT)
# if __has_attribute(warn_unused_result)
#  define SWIFT_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
# else
#  define SWIFT_WARN_UNUSED_RESULT 
# endif
#endif
#if !defined(SWIFT_NORETURN)
# if __has_attribute(noreturn)
#  define SWIFT_NORETURN __attribute__((noreturn))
# else
#  define SWIFT_NORETURN 
# endif
#endif
#if !defined(SWIFT_CLASS_EXTRA)
# define SWIFT_CLASS_EXTRA 
#endif
#if !defined(SWIFT_PROTOCOL_EXTRA)
# define SWIFT_PROTOCOL_EXTRA 
#endif
#if !defined(SWIFT_ENUM_EXTRA)
# define SWIFT_ENUM_EXTRA 
#endif
#if !defined(SWIFT_CLASS)
# if __has_attribute(objc_subclassing_restricted)
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# else
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# endif
#endif
#if !defined(SWIFT_RESILIENT_CLASS)
# if __has_attribute(objc_class_stub)
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME) __attribute__((objc_class_stub))
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_class_stub)) SWIFT_CLASS_NAMED(SWIFT_NAME)
# else
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME)
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) SWIFT_CLASS_NAMED(SWIFT_NAME)
# endif
#endif
#if !defined(SWIFT_PROTOCOL)
# define SWIFT_PROTOCOL(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
# define SWIFT_PROTOCOL_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
#endif
#if !defined(SWIFT_EXTENSION)
# define SWIFT_EXTENSION(M) SWIFT_PASTE(M##_Swift_, __LINE__)
#endif
#if !defined(OBJC_DESIGNATED_INITIALIZER)
# if __has_attribute(objc_designated_initializer)
#  define OBJC_DESIGNATED_INITIALIZER __attribute__((objc_designated_initializer))
# else
#  define OBJC_DESIGNATED_INITIALIZER 
# endif
#endif
#if !defined(SWIFT_ENUM_ATTR)
# if __has_attribute(enum_extensibility)
#  define SWIFT_ENUM_ATTR(_extensibility) __attribute__((enum_extensibility(_extensibility)))
# else
#  define SWIFT_ENUM_ATTR(_extensibility) 
# endif
#endif
#if !defined(SWIFT_ENUM)
# define SWIFT_ENUM(_type, _name, _extensibility) enum _name : _type _name; enum SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# if __has_feature(generalized_swift_name)
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) enum _name : _type _name SWIFT_COMPILE_NAME(SWIFT_NAME); enum SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# else
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) SWIFT_ENUM(_type, _name, _extensibility)
# endif
#endif
#if !defined(SWIFT_UNAVAILABLE)
# define SWIFT_UNAVAILABLE __attribute__((unavailable))
#endif
#if !defined(SWIFT_UNAVAILABLE_MSG)
# define SWIFT_UNAVAILABLE_MSG(msg) __attribute__((unavailable(msg)))
#endif
#if !defined(SWIFT_AVAILABILITY)
# define SWIFT_AVAILABILITY(plat, ...) __attribute__((availability(plat, __VA_ARGS__)))
#endif
#if !defined(SWIFT_WEAK_IMPORT)
# define SWIFT_WEAK_IMPORT __attribute__((weak_import))
#endif
#if !defined(SWIFT_DEPRECATED)
# define SWIFT_DEPRECATED __attribute__((deprecated))
#endif
#if !defined(SWIFT_DEPRECATED_MSG)
# define SWIFT_DEPRECATED_MSG(...) __attribute__((deprecated(__VA_ARGS__)))
#endif
#if !defined(SWIFT_DEPRECATED_OBJC)
# if __has_feature(attribute_diagnose_if_objc)
#  define SWIFT_DEPRECATED_OBJC(Msg) __attribute__((diagnose_if(1, Msg, "warning")))
# else
#  define SWIFT_DEPRECATED_OBJC(Msg) SWIFT_DEPRECATED_MSG(Msg)
# endif
#endif
#if defined(__OBJC__)
#if !defined(IBSegueAction)
# define IBSegueAction 
#endif
#endif
#if !defined(SWIFT_EXTERN)
# if defined(__cplusplus)
#  define SWIFT_EXTERN extern "C"
# else
#  define SWIFT_EXTERN extern
# endif
#endif
#if !defined(SWIFT_CALL)
# define SWIFT_CALL __attribute__((swiftcall))
#endif
#if !defined(SWIFT_INDIRECT_RESULT)
# define SWIFT_INDIRECT_RESULT __attribute__((swift_indirect_result))
#endif
#if !defined(SWIFT_CONTEXT)
# define SWIFT_CONTEXT __attribute__((swift_context))
#endif
#if !defined(SWIFT_ERROR_RESULT)
# define SWIFT_ERROR_RESULT __attribute__((swift_error_result))
#endif
#if defined(__cplusplus)
# define SWIFT_NOEXCEPT noexcept
#else
# define SWIFT_NOEXCEPT 
#endif
#if !defined(SWIFT_C_INLINE_THUNK)
# if __has_attribute(always_inline)
# if __has_attribute(nodebug)
#  define SWIFT_C_INLINE_THUNK inline __attribute__((always_inline)) __attribute__((nodebug))
# else
#  define SWIFT_C_INLINE_THUNK inline __attribute__((always_inline))
# endif
# else
#  define SWIFT_C_INLINE_THUNK inline
# endif
#endif
#if defined(_WIN32)
#if !defined(SWIFT_IMPORT_STDLIB_SYMBOL)
# define SWIFT_IMPORT_STDLIB_SYMBOL __declspec(dllimport)
#endif
#else
#if !defined(SWIFT_IMPORT_STDLIB_SYMBOL)
# define SWIFT_IMPORT_STDLIB_SYMBOL 
#endif
#endif
#if defined(__OBJC__)
#if __has_feature(objc_modules)
#if __has_warning("-Watimport-in-framework-header")
#pragma clang diagnostic ignored "-Watimport-in-framework-header"
#endif
@import BraintreeCore;
@import BraintreePayPal;
@import ObjectiveC;
#endif

#endif
#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"
#if __has_warning("-Wpragma-clang-attribute")
# pragma clang diagnostic ignored "-Wpragma-clang-attribute"
#endif
#pragma clang diagnostic ignored "-Wunknown-pragmas"
#pragma clang diagnostic ignored "-Wnullability"
#pragma clang diagnostic ignored "-Wdollar-in-identifier-extension"

#if __has_attribute(external_source_symbol)
# pragma push_macro("any")
# undef any
# pragma clang attribute push(__attribute__((external_source_symbol(language="Swift", defined_in="BraintreePayPalNativeCheckout",generated_declaration))), apply_to=any(function,enum,objc_interface,objc_category,objc_protocol))
# pragma pop_macro("any")
#endif

#if defined(__OBJC__)
@class NSString;
@class BTPostalAddress;

SWIFT_RESILIENT_CLASS("_TtC29BraintreePayPalNativeCheckout34BTPayPalNativeCheckoutAccountNonce") SWIFT_DEPRECATED_MSG("BraintreePayPalNativeCheckout Module is deprecated, use BraintreePayPal Module instead")
@interface BTPayPalNativeCheckoutAccountNonce : BTPaymentMethodNonce
/// Payer’s email address.
@property (nonatomic, readonly, copy) NSString * _Nullable email;
/// Payer’s first name.
@property (nonatomic, readonly, copy) NSString * _Nullable firstName;
/// Payer’s last name.
@property (nonatomic, readonly, copy) NSString * _Nullable lastName;
/// Payer’s phone number.
@property (nonatomic, readonly, copy) NSString * _Nullable phone;
/// The billing address.
@property (nonatomic, readonly, strong) BTPostalAddress * _Nullable billingAddress;
/// The shipping address.
@property (nonatomic, readonly, strong) BTPostalAddress * _Nullable shippingAddress;
/// Client metadata id associated with this transaction.
@property (nonatomic, readonly, copy) NSString * _Nullable clientMetadataID;
/// Optional. Payer id associated with this transaction.
/// Will be provided for Vault and Checkout.
@property (nonatomic, readonly, copy) NSString * _Nullable payerID;
- (nonnull instancetype)initWithNonce:(NSString * _Nonnull)nonce SWIFT_UNAVAILABLE;
- (nonnull instancetype)initWithNonce:(NSString * _Nonnull)nonce type:(NSString * _Nonnull)type SWIFT_UNAVAILABLE;
- (nonnull instancetype)initWithNonce:(NSString * _Nonnull)nonce type:(NSString * _Nonnull)type isDefault:(BOOL)isDefault SWIFT_UNAVAILABLE;
@end

@class BTAPIClient;
@class BTPayPalNativeCheckoutRequest;
@class BTPayPalNativeVaultRequest;

SWIFT_CLASS("_TtC29BraintreePayPalNativeCheckout28BTPayPalNativeCheckoutClient") SWIFT_DEPRECATED_MSG("BraintreePayPalNativeCheckout Module is deprecated, use BraintreePayPal Module instead")
@interface BTPayPalNativeCheckoutClient : NSObject
- (nonnull instancetype)initWithAPIClient:(BTAPIClient * _Nonnull)apiClient SWIFT_DEPRECATED_MSG("BraintreePayPalNativeCheckout Module is deprecated, use BraintreePayPal Module instead");
- (void)tokenizeWithNativeCheckoutRequest:(BTPayPalNativeCheckoutRequest * _Nonnull)request completion:(void (^ _Nonnull)(BTPayPalNativeCheckoutAccountNonce * _Nullable, NSError * _Nullable))completion SWIFT_DEPRECATED_MSG("BraintreePayPalNativeCheckout Module is deprecated, use BraintreePayPal Module instead");
- (void)tokenizeWithNativeVaultRequest:(BTPayPalNativeVaultRequest * _Nonnull)request completion:(void (^ _Nonnull)(BTPayPalNativeCheckoutAccountNonce * _Nullable, NSError * _Nullable))completion SWIFT_DEPRECATED_MSG("BraintreePayPalNativeCheckout Module is deprecated, use BraintreePayPal Module instead");
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_RESILIENT_CLASS("_TtC29BraintreePayPalNativeCheckout29BTPayPalNativeCheckoutRequest") SWIFT_DEPRECATED_MSG("BraintreePayPalNativeCheckout Module is deprecated, use BraintreePayPal Module instead")
@interface BTPayPalNativeCheckoutRequest : BTPayPalCheckoutRequest
/// Initializes a PayPal Native Checkout request
/// \param amount Used for a one-time payment. Amount must be greater than or equal to zero, may optionally contain exactly 2 decimal places separated by ‘.’
///
/// \param intent Optional: Payment intent. Defaults to <code>.authorize</code>. Only applies to PayPal Checkout.
/// and is limited to 7 digits before the decimal point.
///
/// \param offerPayLater Optional: Offers PayPal Pay Later if the customer qualifies. Defaults to <code>false</code>. Only available with PayPal Checkout.
///
/// \param currencyCode Optional: A three-character ISO-4217 ISO currency code to use for the transaction. Defaults to merchant currency code if not set.
/// See https://developer.paypal.com/docs/api/reference/currency-codes/ for a list of supported currency codes.
///
/// \param requestBillingAgreement Optional: If set to <code>true</code>, this enables the Checkout with Vault flow, where the customer will be prompted to consent to a billing agreement during checkout.
///
/// \param billingAgreementDescription Optional: Display a custom description to the user for a billing agreement. For Checkout with Vault flows, you must also
/// set <code>requestBillingAgreement</code> to <code>true</code> on your <code>BTPayPalNativeVaultRequest</code>.
///
/// \param userAuthenticationEmail Optional: User email to initiate a quicker authentication flow in cases where the user has a PayPal Account with the same email.
///
- (nonnull instancetype)initWithAmount:(NSString * _Nonnull)amount intent:(enum BTPayPalRequestIntent)intent offerPayLater:(BOOL)offerPayLater currencyCode:(NSString * _Nullable)currencyCode requestBillingAgreement:(BOOL)requestBillingAgreement billingAgreementDescription:(NSString * _Nullable)billingAgreementDescription userAuthenticationEmail:(NSString * _Nullable)userAuthenticationEmail OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithAmount:(NSString * _Nonnull)amount intent:(enum BTPayPalRequestIntent)intent userAction:(enum BTPayPalRequestUserAction)userAction offerPayLater:(BOOL)offerPayLater currencyCode:(NSString * _Nullable)currencyCode requestBillingAgreement:(BOOL)requestBillingAgreement SWIFT_UNAVAILABLE;
@end


SWIFT_RESILIENT_CLASS("_TtC29BraintreePayPalNativeCheckout26BTPayPalNativeVaultRequest") SWIFT_DEPRECATED_MSG("BraintreePayPalNativeCheckout Module is deprecated, use BraintreePayPal Module instead")
@interface BTPayPalNativeVaultRequest : BTPayPalVaultBaseRequest
/// Initializes a PayPal Native Vault request
/// \param offerCredit Optional: Offers PayPal Credit if the customer qualifies. Defaults to <code>false</code>.
///
/// \param billingAgreementDescription Optional: Display a custom description to the user for a billing agreement. For Checkout with Vault flows, you must also set
/// <code>requestBillingAgreement</code> to <code>true</code> on your <code>BTPayPalCheckoutRequest</code>.
///
- (nonnull instancetype)initWithOfferCredit:(BOOL)offerCredit billingAgreementDescription:(NSString * _Nullable)billingAgreementDescription OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithOfferCredit:(BOOL)offerCredit SWIFT_UNAVAILABLE;
@end


#endif
#if __has_attribute(external_source_symbol)
# pragma clang attribute pop
#endif
#if defined(__cplusplus)
#endif
#pragma clang diagnostic pop
#endif

#elif defined(__x86_64__) && __x86_64__
// Generated by Apple Swift version 5.9 (swiftlang-5.9.0.128.108 clang-1500.0.40.1)
#ifndef BRAINTREEPAYPALNATIVECHECKOUT_SWIFT_H
#define BRAINTREEPAYPALNATIVECHECKOUT_SWIFT_H
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wgcc-compat"

#if !defined(__has_include)
# define __has_include(x) 0
#endif
#if !defined(__has_attribute)
# define __has_attribute(x) 0
#endif
#if !defined(__has_feature)
# define __has_feature(x) 0
#endif
#if !defined(__has_warning)
# define __has_warning(x) 0
#endif

#if __has_include(<swift/objc-prologue.h>)
# include <swift/objc-prologue.h>
#endif

#pragma clang diagnostic ignored "-Wauto-import"
#if defined(__OBJC__)
#include <Foundation/Foundation.h>
#endif
#if defined(__cplusplus)
#include <cstdint>
#include <cstddef>
#include <cstdbool>
#include <cstring>
#include <stdlib.h>
#include <new>
#include <type_traits>
#else
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>
#include <string.h>
#endif
#if defined(__cplusplus)
#if defined(__arm64e__) && __has_include(<ptrauth.h>)
# include <ptrauth.h>
#else
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wreserved-macro-identifier"
# ifndef __ptrauth_swift_value_witness_function_pointer
#  define __ptrauth_swift_value_witness_function_pointer(x)
# endif
# ifndef __ptrauth_swift_class_method_pointer
#  define __ptrauth_swift_class_method_pointer(x)
# endif
#pragma clang diagnostic pop
#endif
#endif

#if !defined(SWIFT_TYPEDEFS)
# define SWIFT_TYPEDEFS 1
# if __has_include(<uchar.h>)
#  include <uchar.h>
# elif !defined(__cplusplus)
typedef uint_least16_t char16_t;
typedef uint_least32_t char32_t;
# endif
typedef float swift_float2  __attribute__((__ext_vector_type__(2)));
typedef float swift_float3  __attribute__((__ext_vector_type__(3)));
typedef float swift_float4  __attribute__((__ext_vector_type__(4)));
typedef double swift_double2  __attribute__((__ext_vector_type__(2)));
typedef double swift_double3  __attribute__((__ext_vector_type__(3)));
typedef double swift_double4  __attribute__((__ext_vector_type__(4)));
typedef int swift_int2  __attribute__((__ext_vector_type__(2)));
typedef int swift_int3  __attribute__((__ext_vector_type__(3)));
typedef int swift_int4  __attribute__((__ext_vector_type__(4)));
typedef unsigned int swift_uint2  __attribute__((__ext_vector_type__(2)));
typedef unsigned int swift_uint3  __attribute__((__ext_vector_type__(3)));
typedef unsigned int swift_uint4  __attribute__((__ext_vector_type__(4)));
#endif

#if !defined(SWIFT_PASTE)
# define SWIFT_PASTE_HELPER(x, y) x##y
# define SWIFT_PASTE(x, y) SWIFT_PASTE_HELPER(x, y)
#endif
#if !defined(SWIFT_METATYPE)
# define SWIFT_METATYPE(X) Class
#endif
#if !defined(SWIFT_CLASS_PROPERTY)
# if __has_feature(objc_class_property)
#  define SWIFT_CLASS_PROPERTY(...) __VA_ARGS__
# else
#  define SWIFT_CLASS_PROPERTY(...) 
# endif
#endif
#if !defined(SWIFT_RUNTIME_NAME)
# if __has_attribute(objc_runtime_name)
#  define SWIFT_RUNTIME_NAME(X) __attribute__((objc_runtime_name(X)))
# else
#  define SWIFT_RUNTIME_NAME(X) 
# endif
#endif
#if !defined(SWIFT_COMPILE_NAME)
# if __has_attribute(swift_name)
#  define SWIFT_COMPILE_NAME(X) __attribute__((swift_name(X)))
# else
#  define SWIFT_COMPILE_NAME(X) 
# endif
#endif
#if !defined(SWIFT_METHOD_FAMILY)
# if __has_attribute(objc_method_family)
#  define SWIFT_METHOD_FAMILY(X) __attribute__((objc_method_family(X)))
# else
#  define SWIFT_METHOD_FAMILY(X) 
# endif
#endif
#if !defined(SWIFT_NOESCAPE)
# if __has_attribute(noescape)
#  define SWIFT_NOESCAPE __attribute__((noescape))
# else
#  define SWIFT_NOESCAPE 
# endif
#endif
#if !defined(SWIFT_RELEASES_ARGUMENT)
# if __has_attribute(ns_consumed)
#  define SWIFT_RELEASES_ARGUMENT __attribute__((ns_consumed))
# else
#  define SWIFT_RELEASES_ARGUMENT 
# endif
#endif
#if !defined(SWIFT_WARN_UNUSED_RESULT)
# if __has_attribute(warn_unused_result)
#  define SWIFT_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
# else
#  define SWIFT_WARN_UNUSED_RESULT 
# endif
#endif
#if !defined(SWIFT_NORETURN)
# if __has_attribute(noreturn)
#  define SWIFT_NORETURN __attribute__((noreturn))
# else
#  define SWIFT_NORETURN 
# endif
#endif
#if !defined(SWIFT_CLASS_EXTRA)
# define SWIFT_CLASS_EXTRA 
#endif
#if !defined(SWIFT_PROTOCOL_EXTRA)
# define SWIFT_PROTOCOL_EXTRA 
#endif
#if !defined(SWIFT_ENUM_EXTRA)
# define SWIFT_ENUM_EXTRA 
#endif
#if !defined(SWIFT_CLASS)
# if __has_attribute(objc_subclassing_restricted)
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# else
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# endif
#endif
#if !defined(SWIFT_RESILIENT_CLASS)
# if __has_attribute(objc_class_stub)
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME) __attribute__((objc_class_stub))
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_class_stub)) SWIFT_CLASS_NAMED(SWIFT_NAME)
# else
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME)
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) SWIFT_CLASS_NAMED(SWIFT_NAME)
# endif
#endif
#if !defined(SWIFT_PROTOCOL)
# define SWIFT_PROTOCOL(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
# define SWIFT_PROTOCOL_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
#endif
#if !defined(SWIFT_EXTENSION)
# define SWIFT_EXTENSION(M) SWIFT_PASTE(M##_Swift_, __LINE__)
#endif
#if !defined(OBJC_DESIGNATED_INITIALIZER)
# if __has_attribute(objc_designated_initializer)
#  define OBJC_DESIGNATED_INITIALIZER __attribute__((objc_designated_initializer))
# else
#  define OBJC_DESIGNATED_INITIALIZER 
# endif
#endif
#if !defined(SWIFT_ENUM_ATTR)
# if __has_attribute(enum_extensibility)
#  define SWIFT_ENUM_ATTR(_extensibility) __attribute__((enum_extensibility(_extensibility)))
# else
#  define SWIFT_ENUM_ATTR(_extensibility) 
# endif
#endif
#if !defined(SWIFT_ENUM)
# define SWIFT_ENUM(_type, _name, _extensibility) enum _name : _type _name; enum SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# if __has_feature(generalized_swift_name)
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) enum _name : _type _name SWIFT_COMPILE_NAME(SWIFT_NAME); enum SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# else
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) SWIFT_ENUM(_type, _name, _extensibility)
# endif
#endif
#if !defined(SWIFT_UNAVAILABLE)
# define SWIFT_UNAVAILABLE __attribute__((unavailable))
#endif
#if !defined(SWIFT_UNAVAILABLE_MSG)
# define SWIFT_UNAVAILABLE_MSG(msg) __attribute__((unavailable(msg)))
#endif
#if !defined(SWIFT_AVAILABILITY)
# define SWIFT_AVAILABILITY(plat, ...) __attribute__((availability(plat, __VA_ARGS__)))
#endif
#if !defined(SWIFT_WEAK_IMPORT)
# define SWIFT_WEAK_IMPORT __attribute__((weak_import))
#endif
#if !defined(SWIFT_DEPRECATED)
# define SWIFT_DEPRECATED __attribute__((deprecated))
#endif
#if !defined(SWIFT_DEPRECATED_MSG)
# define SWIFT_DEPRECATED_MSG(...) __attribute__((deprecated(__VA_ARGS__)))
#endif
#if !defined(SWIFT_DEPRECATED_OBJC)
# if __has_feature(attribute_diagnose_if_objc)
#  define SWIFT_DEPRECATED_OBJC(Msg) __attribute__((diagnose_if(1, Msg, "warning")))
# else
#  define SWIFT_DEPRECATED_OBJC(Msg) SWIFT_DEPRECATED_MSG(Msg)
# endif
#endif
#if defined(__OBJC__)
#if !defined(IBSegueAction)
# define IBSegueAction 
#endif
#endif
#if !defined(SWIFT_EXTERN)
# if defined(__cplusplus)
#  define SWIFT_EXTERN extern "C"
# else
#  define SWIFT_EXTERN extern
# endif
#endif
#if !defined(SWIFT_CALL)
# define SWIFT_CALL __attribute__((swiftcall))
#endif
#if !defined(SWIFT_INDIRECT_RESULT)
# define SWIFT_INDIRECT_RESULT __attribute__((swift_indirect_result))
#endif
#if !defined(SWIFT_CONTEXT)
# define SWIFT_CONTEXT __attribute__((swift_context))
#endif
#if !defined(SWIFT_ERROR_RESULT)
# define SWIFT_ERROR_RESULT __attribute__((swift_error_result))
#endif
#if defined(__cplusplus)
# define SWIFT_NOEXCEPT noexcept
#else
# define SWIFT_NOEXCEPT 
#endif
#if !defined(SWIFT_C_INLINE_THUNK)
# if __has_attribute(always_inline)
# if __has_attribute(nodebug)
#  define SWIFT_C_INLINE_THUNK inline __attribute__((always_inline)) __attribute__((nodebug))
# else
#  define SWIFT_C_INLINE_THUNK inline __attribute__((always_inline))
# endif
# else
#  define SWIFT_C_INLINE_THUNK inline
# endif
#endif
#if defined(_WIN32)
#if !defined(SWIFT_IMPORT_STDLIB_SYMBOL)
# define SWIFT_IMPORT_STDLIB_SYMBOL __declspec(dllimport)
#endif
#else
#if !defined(SWIFT_IMPORT_STDLIB_SYMBOL)
# define SWIFT_IMPORT_STDLIB_SYMBOL 
#endif
#endif
#if defined(__OBJC__)
#if __has_feature(objc_modules)
#if __has_warning("-Watimport-in-framework-header")
#pragma clang diagnostic ignored "-Watimport-in-framework-header"
#endif
@import BraintreeCore;
@import BraintreePayPal;
@import ObjectiveC;
#endif

#endif
#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"
#if __has_warning("-Wpragma-clang-attribute")
# pragma clang diagnostic ignored "-Wpragma-clang-attribute"
#endif
#pragma clang diagnostic ignored "-Wunknown-pragmas"
#pragma clang diagnostic ignored "-Wnullability"
#pragma clang diagnostic ignored "-Wdollar-in-identifier-extension"

#if __has_attribute(external_source_symbol)
# pragma push_macro("any")
# undef any
# pragma clang attribute push(__attribute__((external_source_symbol(language="Swift", defined_in="BraintreePayPalNativeCheckout",generated_declaration))), apply_to=any(function,enum,objc_interface,objc_category,objc_protocol))
# pragma pop_macro("any")
#endif

#if defined(__OBJC__)
@class NSString;
@class BTPostalAddress;

SWIFT_RESILIENT_CLASS("_TtC29BraintreePayPalNativeCheckout34BTPayPalNativeCheckoutAccountNonce") SWIFT_DEPRECATED_MSG("BraintreePayPalNativeCheckout Module is deprecated, use BraintreePayPal Module instead")
@interface BTPayPalNativeCheckoutAccountNonce : BTPaymentMethodNonce
/// Payer’s email address.
@property (nonatomic, readonly, copy) NSString * _Nullable email;
/// Payer’s first name.
@property (nonatomic, readonly, copy) NSString * _Nullable firstName;
/// Payer’s last name.
@property (nonatomic, readonly, copy) NSString * _Nullable lastName;
/// Payer’s phone number.
@property (nonatomic, readonly, copy) NSString * _Nullable phone;
/// The billing address.
@property (nonatomic, readonly, strong) BTPostalAddress * _Nullable billingAddress;
/// The shipping address.
@property (nonatomic, readonly, strong) BTPostalAddress * _Nullable shippingAddress;
/// Client metadata id associated with this transaction.
@property (nonatomic, readonly, copy) NSString * _Nullable clientMetadataID;
/// Optional. Payer id associated with this transaction.
/// Will be provided for Vault and Checkout.
@property (nonatomic, readonly, copy) NSString * _Nullable payerID;
- (nonnull instancetype)initWithNonce:(NSString * _Nonnull)nonce SWIFT_UNAVAILABLE;
- (nonnull instancetype)initWithNonce:(NSString * _Nonnull)nonce type:(NSString * _Nonnull)type SWIFT_UNAVAILABLE;
- (nonnull instancetype)initWithNonce:(NSString * _Nonnull)nonce type:(NSString * _Nonnull)type isDefault:(BOOL)isDefault SWIFT_UNAVAILABLE;
@end

@class BTAPIClient;
@class BTPayPalNativeCheckoutRequest;
@class BTPayPalNativeVaultRequest;

SWIFT_CLASS("_TtC29BraintreePayPalNativeCheckout28BTPayPalNativeCheckoutClient") SWIFT_DEPRECATED_MSG("BraintreePayPalNativeCheckout Module is deprecated, use BraintreePayPal Module instead")
@interface BTPayPalNativeCheckoutClient : NSObject
- (nonnull instancetype)initWithAPIClient:(BTAPIClient * _Nonnull)apiClient SWIFT_DEPRECATED_MSG("BraintreePayPalNativeCheckout Module is deprecated, use BraintreePayPal Module instead");
- (void)tokenizeWithNativeCheckoutRequest:(BTPayPalNativeCheckoutRequest * _Nonnull)request completion:(void (^ _Nonnull)(BTPayPalNativeCheckoutAccountNonce * _Nullable, NSError * _Nullable))completion SWIFT_DEPRECATED_MSG("BraintreePayPalNativeCheckout Module is deprecated, use BraintreePayPal Module instead");
- (void)tokenizeWithNativeVaultRequest:(BTPayPalNativeVaultRequest * _Nonnull)request completion:(void (^ _Nonnull)(BTPayPalNativeCheckoutAccountNonce * _Nullable, NSError * _Nullable))completion SWIFT_DEPRECATED_MSG("BraintreePayPalNativeCheckout Module is deprecated, use BraintreePayPal Module instead");
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_RESILIENT_CLASS("_TtC29BraintreePayPalNativeCheckout29BTPayPalNativeCheckoutRequest") SWIFT_DEPRECATED_MSG("BraintreePayPalNativeCheckout Module is deprecated, use BraintreePayPal Module instead")
@interface BTPayPalNativeCheckoutRequest : BTPayPalCheckoutRequest
/// Initializes a PayPal Native Checkout request
/// \param amount Used for a one-time payment. Amount must be greater than or equal to zero, may optionally contain exactly 2 decimal places separated by ‘.’
///
/// \param intent Optional: Payment intent. Defaults to <code>.authorize</code>. Only applies to PayPal Checkout.
/// and is limited to 7 digits before the decimal point.
///
/// \param offerPayLater Optional: Offers PayPal Pay Later if the customer qualifies. Defaults to <code>false</code>. Only available with PayPal Checkout.
///
/// \param currencyCode Optional: A three-character ISO-4217 ISO currency code to use for the transaction. Defaults to merchant currency code if not set.
/// See https://developer.paypal.com/docs/api/reference/currency-codes/ for a list of supported currency codes.
///
/// \param requestBillingAgreement Optional: If set to <code>true</code>, this enables the Checkout with Vault flow, where the customer will be prompted to consent to a billing agreement during checkout.
///
/// \param billingAgreementDescription Optional: Display a custom description to the user for a billing agreement. For Checkout with Vault flows, you must also
/// set <code>requestBillingAgreement</code> to <code>true</code> on your <code>BTPayPalNativeVaultRequest</code>.
///
/// \param userAuthenticationEmail Optional: User email to initiate a quicker authentication flow in cases where the user has a PayPal Account with the same email.
///
- (nonnull instancetype)initWithAmount:(NSString * _Nonnull)amount intent:(enum BTPayPalRequestIntent)intent offerPayLater:(BOOL)offerPayLater currencyCode:(NSString * _Nullable)currencyCode requestBillingAgreement:(BOOL)requestBillingAgreement billingAgreementDescription:(NSString * _Nullable)billingAgreementDescription userAuthenticationEmail:(NSString * _Nullable)userAuthenticationEmail OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithAmount:(NSString * _Nonnull)amount intent:(enum BTPayPalRequestIntent)intent userAction:(enum BTPayPalRequestUserAction)userAction offerPayLater:(BOOL)offerPayLater currencyCode:(NSString * _Nullable)currencyCode requestBillingAgreement:(BOOL)requestBillingAgreement SWIFT_UNAVAILABLE;
@end


SWIFT_RESILIENT_CLASS("_TtC29BraintreePayPalNativeCheckout26BTPayPalNativeVaultRequest") SWIFT_DEPRECATED_MSG("BraintreePayPalNativeCheckout Module is deprecated, use BraintreePayPal Module instead")
@interface BTPayPalNativeVaultRequest : BTPayPalVaultBaseRequest
/// Initializes a PayPal Native Vault request
/// \param offerCredit Optional: Offers PayPal Credit if the customer qualifies. Defaults to <code>false</code>.
///
/// \param billingAgreementDescription Optional: Display a custom description to the user for a billing agreement. For Checkout with Vault flows, you must also set
/// <code>requestBillingAgreement</code> to <code>true</code> on your <code>BTPayPalCheckoutRequest</code>.
///
- (nonnull instancetype)initWithOfferCredit:(BOOL)offerCredit billingAgreementDescription:(NSString * _Nullable)billingAgreementDescription OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithOfferCredit:(BOOL)offerCredit SWIFT_UNAVAILABLE;
@end


#endif
#if __has_attribute(external_source_symbol)
# pragma clang attribute pop
#endif
#if defined(__cplusplus)
#endif
#pragma clang diagnostic pop
#endif

#else
#error unsupported Swift architecture
#endif
